dist: trusty
language: java
script: mvn install
sudo: false
after_success:
  - mvn clean test jacoco:report coveralls:report
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
